//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Expenses { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
